### PR TITLE
Time graph limit fix

### PR DESCRIPTION
**Pull request by farisdurrani**

### CODE REVIEW

**Review by benjaminboeckman — CHANGES_REQUESTED** [review]
I noticed that you have a hunk of code that gets called in different scene's update_passive methods, so I was wondering if you could add it to the MainWindow's update_passive method for simplicity and for ease of change in the future. Other than that, it looks great!

**Review by Ahellrigel33 — APPROVED** [review]
Looks good, add fix for not resetting data for new scenes.

**Review by Ahellrigel33 — APPROVED** [review]
Fixing it so that it still resets on the first run looks good to me.

**Review by benjaminboeckman — CHANGES_REQUESTED** [review]
As you demonstrated to me before, Faris, the functionality looks great and the cleanups are very helpful for testing especially being able to see the graphs displayed before clicking "Start Collecting Data."

One thing I noticed, though, is that the "Select All" checkbox seems to break the logic of the graphs being updated prior to clicking "Start Collecting Data." That's all that I noticed in testing, so apart from that, I'm looking forward to adding these changes to dev branch.

Thanks for all your hard work, Faris!

**Comment by farisdurrani** [comment]
@benjaminboeckman I've fixed that Select All checkbox issue, along with another issue regarding the settings button which I missed. Right now, Andrew has asked me to make some additional changes (collecting data from time 0 and starting data collection as soon as closing the Save window). So I'll be working on those. You can merge what we have now if you want, or wait until those features are done

**Pull request closed without merging**
